import { tsxRuby } from "./examples/tsx.js";
import { firstRuby } from "./examples/first-ruby.js";
import { readings } from "./examples/readings.js";
import { correspondence } from "./examples/correspondence.js";
import { dictionary } from "./examples/dictionary.js";
import { analysis } from "./examples/analysis.js";
import { styling } from "./examples/styling.js";
import { defaults } from "./examples/defaults.js";
import { custom } from "./examples/custom.js";
import { errors } from "./examples/errors.js";
import { unidic } from "./examples/unidic.js";
import { docsDirectory } from "./context.js";
import type { Example } from "./types.js";

const source = (name: string) => new URL(`src/examples/${name}.ts`, docsDirectory);
export const examples: Example[] = [
  {
    section: "Quick Start", title: "Your first ruby paragraph", sourceFile: source("first-ruby"), render: firstRuby,
    description: "Create an instance, await its autoRuby method, and place the returned inlines in a paragraph. The complete document wrapper and local installation commands are on the following reference pages and in the README.",
    note: "p() accepts a two-dimensional inline array: [await r.autoRuby(text)] describes one line. The result is generated by the exact code above. All manual examples are executed during the build.",
  },
  {
    section: "Quick Start", title: "Using TSX", sourceFile: new URL("src/examples/tsx.tsx", docsDirectory), render: tsxRuby,
    description: "Install @minitype/tsx and set jsx to react-jsx and jsxImportSource to @minitype/tsx in tsconfig.json. AutoRuby accepts text children and RubyOptions as props and expands synchronously during JSX evaluation.",
    note: "Pass the document directly to minitypeJSX(document).save(path). Use createAutoRuby(config) for component-wide defaults or a synchronous custom tokenizer. See examples/tsx.tsx for a complete document.",
  },
  {
    section: "Usage", title: "Correspondence and grouping", sourceFile: source("correspondence"), render: correspondence,
    description: "Compare correspondence lookup, tokenizer-only analysis and whole-token ruby. With correspondence, 東京 is split into 東(とう)京(きょう); tokenizer-only keeps 東京(とうきょう) together. The readings can sound identical while their ruby grouping differs.",
    note: "granularity: word includes okurigana in each annotated token. correspondence: false skips the correspondence WASM and keeps kana alignment. It does not disable morphological analysis.",
  },
  {
    section: "Usage", title: "Explicit readings and exclusions", sourceFile: source("readings"), render: readings,
    description: "Specify the reading of Akabanebashi Station explicitly, and leave Tokyo Tower unannotated. These replacements are useful for intended readings that cannot be inferred from the surrounding sentence.",
    note: "Overrides choose the longest match at each position and bypass correspondence. Text around matches is analyzed in separate chunks, which can change context. Use userDictionary when tokenization context must be retained.",
  },
  {
    section: "Usage", title: "User dictionaries", sourceFile: source("dictionary"), render: dictionary,
    description: "Load a UTF-8 CSV file to add a word to Lindera's lattice. assets/dictionary.csv contains: 赤羽橋駅,カスタム名詞,アカバネバシエキ. Compare the default reading above with the corrected reading below.",
    note: "Use a path relative to the working directory or a file URL. Files reload on each call. Specify either userDictionary or userDictionaryPath; a call-level source replaces the instance source. Missing files and invalid CSV reject the call.",
  },
  {
    section: "Usage", title: "Hiragana and katakana", sourceFile: source("styling"), render: styling,
    description: "Compare the same sentence with hiragana ruby on the first line and katakana ruby on the second. Both lines use UniDic and the same minitype styles; only the kana option changes.",
    note: "Numeric minitype lengths are millimeters; pt() and em() express other units. Use sufficient lineHeight for the chosen ruby size and gap. Document-wide defaults belong in block.paragraph.",
  },
  {
    section: "Usage", title: "Instance defaults and overrides", sourceFile: source("defaults"), render: defaults,
    description: "Instance settings provide defaults for each call. A call replaces scalar options and merges reading entries by surface. The first paragraph leaves Tokyo Tower unannotated; the second supplies its reading in hiragana.",
    note: "A call-level userDictionary string replaces the instance CSV; strings are not concatenated. Top-level autoRuby(), analyze() and segments() use a shared default instance.",
  },
  {
    section: "Usage", title: "Analysis table", sourceFile: source("analysis"), render: analysis, captionKind: "Table",
    description: "Build a table directly from analyze(). Each row shows a token, its reading, part of speech and original text range. This example uses UniDic; a dash indicates a missing value.",
    note: "Offsets are UTF-16 indices with an exclusive end. text.slice(start, end) reproduces the token surface. autoRuby() renders segments directly. rubyKind is informational metadata and does not select a minitype layout mode.",
  },
  {
    section: "Usage", title: "Custom tokenizers", sourceFile: source("custom"), render: custom,
    description: "A custom callback avoids loading the bundled WASM. This intentionally narrow example supplies the sentence and its punctuation separately. Kana-anchor alignment separates the okurigana.",
    note: "Production callbacks must preserve surface text and order. They receive a second argument with userDictionary and correspondence settings and decide how to honor them. Optional segments can provide explicit correspondence.",
  },
  {
    section: "Usage", title: "Validation and errors", sourceFile: source("errors"), render: errors,
    description: "Invalid user CSV rejects before it enters the analyzer. The message below is captured at build time, followed by a successful analysis to show that the failure does not corrupt the next request.",
    note: "Other failures include invalid kana or granularity options, missing assets and custom tokenizers that lose text. Catch rejected promises at your application's boundary.",
  },
  {
    section: "Usage", title: "Choosing UniDic", sourceFile: source("unidic"), render: unidic,
    description: "The first line uses IPADIC, which leaves 淹 unannotated in this sentence. The second uses UniDic, which supplies い. Select a dictionary on an instance or an individual call.",
    note: "The bundled dictionaries differ in vocabulary and tokenization; UniDic is not necessarily more accurate for every sentence. correspondence: false skips correspondence lookup while retaining the analyzer's reading reconstruction. Only the selected analyzer loads at runtime.",
  },
];
